= C++ example project scanned on SonarCloud using Bitbucket Cloud pipelines
// TODO: add SC status
// TODO: add link to SC

To analyze a C/C++/Objective-C project on Bitbucket pipelines with SonarCloud, follow the steps described here: https://sonarcloud.io/documentation/getting-started/bitbucket-cloud/[Getting started with Bitbucket Cloud].

To sum up, you need to:

. Enable pipelines in your Bitbucket Cloud repository
. Add a repository variable `SONAR_TOKEN` with the value given by SonarCloud during the setup
. In your `bitbucket-pipelines.yml` file:
.. Download the https://sonarcloud.io/documentation/analysis/languages/cfamily/#analysis-steps-using-build-wrapper[`build wrapper`] and wrap your compilation with it
.. Download and launch https://sonarcloud.io/documentation/analysis/scan/sonarscanner/[`sonar-scanner`]

You can take a look at the link:sonar-project.properties[sonar-project.properties] and link:bitbucket-pipelines.yml[bitbucket-pipelines.yml] to see it in practice.

= Documentation

- https://docs.sonarqube.org/latest/analysis/languages/cfamily/[Documentation of the C/C++/Objective-C plugin and its Build Wrapper]
- https://sonarcloud.io/documentation/reference/bitbucket-integration/[Bitbucket Cloud Integration]
- https://sonarcloud.io/documentation/reference/ci/bitbucket-pipelines/[Analyze your repository with Bitbucket Pipelines]

= Linux\Autotools

A build of the https://github.com/sc-sq-c-family-examples/code[code repository] on a Linux platform using GNU Autotools build system.

To build the code run:
----
autoreconf --install
./configure
make clean all
----

= Code Description

An example of a flawed C++ code. The https://github.com/sc-sq-c-family-examples/code[code repository] is meant to be compiled with different build systems using different CI pipelines on Linux, MacOS, and Windows.

The https://github.com/sc-sq-c-family-examples/code[code repository] is forked into other repositories in https://github.com/sc-sq-c-family-examples[this collection] to add a specific build system, platform, and CI.
The downstream repositories are analyzed either with https://www.sonarqube.org/[SonarQube] or https://sonarcloud.io/[SonarCloud].

You can find examples for:

* https://github.com/sc-sq-c-family-examples?q=linux[Linux]
* https://github.com/sc-sq-c-family-examples?q=macos[MacOS]
* https://github.com/sc-sq-c-family-examples?q=windows[Windows]

Using the following build systems:

* https://github.com/sc-sq-c-family-examples?q=cmake[CMake]
* https://github.com/sc-sq-c-family-examples?q=autotools[GNU Autotools]
* https://github.com/sc-sq-c-family-examples?q=xcode[Xcode]
* https://github.com/sc-sq-c-family-examples?q=msbuild[MSBuild]

Running on the following CI services:

* https://github.com/sc-sq-c-family-examples?q=azure[Azure DevOps]
* https://github.com/sc-sq-c-family-examples?q=gh-actions[GitHub Actions]
* https://github.com/sc-sq-c-family-examples?q=travis[Travis]
* https://github.com/sc-sq-c-family-examples?q=jenkins[Jenkins]
* https://github.com/sc-sq-c-family-examples?q=gitlab[GitLab CI]
* https://github.com/sc-sq-c-family-examples?q=bitbucket[BitBucket Pipelines]

Configured for analysis on:

* https://github.com/sc-sq-c-family-examples?q=-sq[SonarQube]
* https://github.com/sc-sq-c-family-examples?q=-sc[SonarCloud]


See link:./examples-structure.adoc[examples-structure.adoc] for a description of the structure of https://github.com/sc-sq-c-family-examples[this GitHub organization] and the relations between its different repositories.
